### ISSUE TITLE
more describe of 2D data and scannet_frames_25k.

### ISSUE THREAD

**Issue by zyrant** [xuxw98/Online3D#2]
hello,

Good work. Can you provide more description of the usage of 2D data and scannet_frames_25k data? Since scannet_frames_25k also provides 2D instance labels.

best wishes.

**Comment by xuxw98** [comment]
Hi,
scannet_frames_25k is for SV-training. It contains downsampled RGB-D frames. So the amount of data is suitable for training SV model.

2D data is for Online-training. Note that we require consistent instance_id across different frames in the same scene / sequence. However, scannet_frames_25k does not provide this consistent annotation.

**Comment by zyrant** [comment]
I get it, thank you for your quick response.

Best Regards

**Comment by zyrant** [comment]
hi，

I have successfully processed the scannet_sv data. It seems that there are some problems when testing a single view. 
I use the following 
```
CUDA_VISIBLE_DEVICES=0 PORT=29544 bash ./tools/dist_test.sh configs/fcaf3d_sv/fcaf3dFF_scannet-3d-18class.py checkpoints/fcaf3d_sv.pth 1 --show-dir work_dirs/debug/ --eval x
```
And encountered these problems:

```Traceback (most recent call last):
  File "./tools/train.py", line 263, in <module>
    main()
  File "./tools/train.py", line 252, in main
    train_model(
  File "/opt/data/private/online3d/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/opt/data/private/online3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 126, in _do_evaluate
    results = multi_gpu_test(
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 165, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/base.py", line 62, in forward
    return self.forward_test(**kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/base.py", line 43, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/single_stage_sparseFF.py", line 113, in simple_test
    if self.evaluator_mode == 'slice_len_constant':
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SingleStageSparse3DDetectorFF' object has no attribute 'evaluator_mode'
```
```
 File "./tools/test.py", line 265, in <module>
    main()
  File "./tools/test.py", line 238, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 165, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/base.py", line 62, in forward
    return self.forward_test(**kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/base.py", line 43, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/opt/data/private/online3d/mmdet3d/models/detectors/single_stage_sparseFF.py", line 121, in simple_test
    num_slice = min(len(points[0]),self.num_slice)
  File "/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SingleStageSparse3DDetectorFF' object has no attribute 'num_slice'
```
Also, it seems that `self.len_slice` is not defined either.

**Comment by xuxw98** [comment]
evaluator_mode, num_slice and len_slice are used for online evaluation only. They should not appear in SV model.

It seems that the simple_test function of SV models are not in the right version. We will check the code and fix this bug.

**Comment by xiac20** [comment]
We have corrected the code errors, and we appreciate your feedback.

**Comment by zyrant** [comment]
Thank you for your useful reply. I am sorry that I encountered some new problems.

It seems the [test.py](https://github.com/xuxw98/Online3D/blob/main/tools/test.py) is not suitable for [scannet_sv](https://github.com/xuxw98/Online3D/blob/main/configs/fcaf3d_sv/fcaf3dFF_scannet-3d-18class.py) to validate with the following
```
CUDA_VISIBLE_DEVICES=0 PORT=29544 bash ./tools/dist_test.sh configs/fcaf3d_sv/fcaf3dFF_scannet-3d-18class.py checkpoints/fcaf3d_sv.pth 1 --show-dir work_dirs/debug/ --eval x
```
```
Traceback (most recent call last):
  File "./tools/test.py", line 265, in <module>
    main()
  File "./tools/test.py", line 261, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
TypeError: evaluate() got an unexpected keyword argument 'scene_name'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 42105) of binary: /home/miniconda3/envs/online/bin/python
```
so I comment on the following line
https://github.com/xuxw98/Online3D/blob/b6a6286480ad0256c1dbfc977babf3e98ea2caf0/tools/test.py#L260

and get the following results. Is it reasonable since the results are much better than those in the [readme](https://github.com/xuxw98/Online3D/blob/main/README.md)?

```
CUDA_VISIBLE_DEVICES=0 PORT=29544 bash ./tools/dist_test.sh configs/fcaf3d_sv/fcaf3dFF_scannet-3d-18class.py checkpoints/fcaf3d_sv.pth 1 --show-dir work_dirs/debug/ --eval x
/home/miniconda3/envs/online/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
/home/miniconda3/envs/online/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
The model and loaded state dict do not match exactly

unexpected key in source state_dict: proposal_generator.rpn_head.conv.weight, proposal_generator.rpn_head.conv.bias, proposal_generator.rpn_head.objectness_logits.weight, proposal_generator.rpn_head.objectness_logits.bias, proposal_generator.rpn_head.anchor_deltas.weight, proposal_generator.rpn_head.anchor_deltas.bias, roi_heads.box_head.fc1.weight, roi_heads.box_head.fc1.bias, roi_heads.box_head.fc2.weight, roi_heads.box_head.fc2.bias, roi_heads.box_predictor.cls_score.weight, roi_heads.box_predictor.cls_score.bias, roi_heads.box_predictor.bbox_pred.weight, roi_heads.box_predictor.bbox_pred.bias, roi_heads.mask_head.mask_fcn1.weight, roi_heads.mask_head.mask_fcn1.bias, roi_heads.mask_head.mask_fcn2.weight, roi_heads.mask_head.mask_fcn2.bias, roi_heads.mask_head.mask_fcn3.weight, roi_heads.mask_head.mask_fcn3.bias, roi_heads.mask_head.mask_fcn4.weight, roi_heads.mask_head.mask_fcn4.bias, roi_heads.mask_head.deconv.weight, roi_heads.mask_head.deconv.bias, roi_heads.mask_head.predictor.weight, roi_heads.mask_head.predictor.bias

load checkpoint from local path: checkpoints/fcaf3d_sv.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5254/5254, 11.0 task/s, elapsed: 476s, ETA:     0s
+----------------+---------+---------+---------+---------+
| classes        | AP_0.25 | AR_0.25 | AP_0.50 | AR_0.50 |
+----------------+---------+---------+---------+---------+
| cabinet        | 0.3830  | 0.8064  | 0.2357  | 0.5859  |
| bed            | 0.6462  | 0.8708  | 0.5215  | 0.7076  |
| chair          | 0.6743  | 0.8400  | 0.5060  | 0.6772  |
| sofa           | 0.6433  | 0.9064  | 0.5235  | 0.7809  |
| table          | 0.4658  | 0.8038  | 0.3238  | 0.5493  |
| door           | 0.3943  | 0.7931  | 0.2082  | 0.5395  |
| window         | 0.4158  | 0.7785  | 0.2032  | 0.5221  |
| bookshelf      | 0.5029  | 0.8517  | 0.3965  | 0.6970  |
| picture        | 0.3222  | 0.5722  | 0.1536  | 0.3218  |
| counter        | 0.4761  | 0.7869  | 0.1811  | 0.3656  |
| desk           | 0.5074  | 0.8639  | 0.3206  | 0.6187  |
| curtain        | 0.4233  | 0.8283  | 0.2546  | 0.6131  |
| refrigerator   | 0.3195  | 0.7244  | 0.1786  | 0.5795  |
| showercurtrain | 0.4745  | 0.8101  | 0.3141  | 0.6592  |
| toilet         | 0.8905  | 0.9520  | 0.7229  | 0.8155  |
| sink           | 0.5344  | 0.7592  | 0.2800  | 0.4791  |
| bathtub        | 0.6898  | 0.8392  | 0.5705  | 0.6734  |
| garbagebin     | 0.3884  | 0.7486  | 0.2893  | 0.5423  |
+----------------+---------+---------+---------+---------+
| Overall        | 0.5084  | 0.8075  | 0.3435  | 0.5960  |
+----------------+---------+---------+---------+---------+
{'cabinet_AP_0.25': 0.38303089141845703, 'bed_AP_0.25': 0.6462198495864868, 'chair_AP_0.25': 0.6742950677871704, 'sofa_AP_0.25': 0.6432637572288513, 'table_AP_0.25': 0.46582460403442383, 'door_AP_0.25': 0.39426273107528687, 'window_AP_0.25': 0.41579222679138184, 'bookshelf_AP_0.25': 0.5028567314147949, 'picture_AP_0.25': 0.322155237197876, 'counter_AP_0.25': 0.4760626554489136, 'desk_AP_0.25': 0.5073734521865845, 'curtain_AP_0.25': 0.4233340620994568, 'refrigerator_AP_0.25': 0.31950151920318604, 'showercurtrain_AP_0.25': 0.474488765001297, 'toilet_AP_0.25': 0.8905090093612671, 'sink_AP_0.25': 0.5344454050064087, 'bathtub_AP_0.25': 0.6898376941680908, 'garbagebin_AP_0.25': 0.3883518874645233, 'mAP_0.25': 0.5084224939346313, 'cabinet_rec_0.25': 0.8063794068270845, 'bed_rec_0.25': 0.8707571801566579, 'chair_rec_0.25': 0.8399682791435369, 'sofa_rec_0.25': 0.9063545150501672, 'table_rec_0.25': 0.8037945395650162, 'door_rec_0.25': 0.7930660888407367, 'window_rec_0.25': 0.778534923339012, 'bookshelf_rec_0.25': 0.8516949152542372, 'picture_rec_0.25': 0.5722120658135283, 'counter_rec_0.25': 0.7869249394673123, 'desk_rec_0.25': 0.8638996138996139, 'curtain_rec_0.25': 0.8283378746594006, 'refrigerator_rec_0.25': 0.7243816254416962, 'showercurtrain_rec_0.25': 0.8100558659217877, 'toilet_rec_0.25': 0.9520295202952029, 'sink_rec_0.25': 0.7592137592137592, 'bathtub_rec_0.25': 0.8391959798994975, 'garbagebin_rec_0.25': 0.7485764345159878, 'mAR_0.25': 0.8075209737391241, 'cabinet_AP_0.50': 0.2356589287519455, 'bed_AP_0.50': 0.5215452909469604, 'chair_AP_0.50': 0.5059803128242493, 'sofa_AP_0.50': 0.5235216617584229, 'table_AP_0.50': 0.32383596897125244, 'door_AP_0.50': 0.2081804871559143, 'window_AP_0.50': 0.20320282876491547, 'bookshelf_AP_0.50': 0.3964529037475586, 'picture_AP_0.50': 0.15361079573631287, 'counter_AP_0.50': 0.18111632764339447, 'desk_AP_0.50': 0.3206106722354889, 'curtain_AP_0.50': 0.2546040415763855, 'refrigerator_AP_0.50': 0.17856290936470032, 'showercurtrain_AP_0.50': 0.3141374886035919, 'toilet_AP_0.50': 0.7229011654853821, 'sink_AP_0.50': 0.27997225522994995, 'bathtub_AP_0.50': 0.570529580116272, 'garbagebin_AP_0.50': 0.2893286943435669, 'mAP_0.50': 0.3435417711734772, 'cabinet_rec_0.50': 0.5858981533296027, 'bed_rec_0.50': 0.7075718015665796, 'chair_rec_0.50': 0.6772402854877082, 'sofa_rec_0.50': 0.7809364548494984, 'table_rec_0.50': 0.5492827394724664, 'door_rec_0.50': 0.5395449620801733, 'window_rec_0.50': 0.5221465076660988, 'bookshelf_rec_0.50': 0.6970338983050848, 'picture_rec_0.50': 0.3217550274223035, 'counter_rec_0.50': 0.36561743341404357, 'desk_rec_0.50': 0.6187258687258688, 'curtain_rec_0.50': 0.6130790190735694, 'refrigerator_rec_0.50': 0.5795053003533569, 'showercurtrain_rec_0.50': 0.659217877094972, 'toilet_rec_0.50': 0.8154981549815498, 'sink_rec_0.50': 0.47911547911547914, 'bathtub_rec_0.50': 0.6733668341708543, 'garbagebin_rec_0.50': 0.5422689443714411, 'mAR_0.50': 0.5959891523044807}

```

**Comment by xuxw98** [comment]
This performance is okay. If I remember correctly, the 41.9 / 20.6 is reported by simply concatenating the boxes from different frames. While in this version of code, we use the merge_and_update operation for better inter-frame processing.

Feel free to contact us if you have any further questions. We also welcome you to submit pull requests to help us fix some undiscovered bugs.

**Comment by xuxw98** [comment]
This performance is okay. If I remember correctly, the 41.9 / 20.6 is reported by simply concatenating the boxes from different frames. While in this version of code, we use the merge_and_update operation for better inter-frame processing.

Feel free to contact us if you have any further questions. We also welcome you to submit pull requests to help us fix some undiscovered bugs.

**Comment by zyrant** [comment]
OK, thank you again for your prompt response.
